In [1]:
import numpy as np
from PIL import Image
import cv2
import glob, random
%matplotlib inline

#変更必要
outfile = "D:/過去の研究データ/2023npz/2023UsingFrontAndBackHands/separateLearn/100sheetsNum20FrontEdgesKarnel5-128pix.npz"
#変更必要
photo_size = 128
x = []
y = []
laplace5 = [[-1, -3, -4, -3, -1],
           [-3, 0, 6, 0, -3],
           [-4, 6, 20, 6, -4],
           [-3, 0, 6, 0, -3],
           [-1, -3, -4, -3, -1]]

def main():
    glob_files("D:/過去の研究データ/2023sheetsHands/aizawa/right/omote", 0)
    glob_files("D:/過去の研究データ/2023sheetsHands/arai/right/omote", 1)
    glob_files("D:/過去の研究データ/2023sheetsHands/ebato/right/omote", 2)
    glob_files("D:/過去の研究データ/2023sheetsHands/hasegawa/right/omote", 3)
    glob_files("D:/過去の研究データ/2023sheetsHands/higuchi/right/omote", 4)
    glob_files("D:/過去の研究データ/2023sheetsHands/isii/right/omote", 5)
    glob_files("D:/過去の研究データ/2023sheetsHands/kojima/right/omote", 6)
    glob_files("D:/過去の研究データ/2023sheetsHands/nakamura/right/omote", 7)
    glob_files("D:/過去の研究データ/2023sheetsHands/oono/right/omote", 8)
    glob_files("D:/過去の研究データ/2023sheetsHands/sakai/right/omote", 9)
    glob_files("D:/過去の研究データ/2023sheetsHands/sekine/right/omote", 10)
    glob_files("D:/過去の研究データ/2023sheetsHands/shimada/right/omote", 11)
    glob_files("D:/過去の研究データ/2023sheetsHands/shimizu/right/omote", 12)
    glob_files("D:/過去の研究データ/2023sheetsHands/takahashi/right/omote", 13)
    glob_files("D:/過去の研究データ/2023sheetsHands/tanakahiroki/right/omote", 14)
    glob_files("D:/過去の研究データ/2023sheetsHands/tanakamiyu/right/omote", 15)
    glob_files("D:/過去の研究データ/2023sheetsHands/tanakataiki/right/omote", 16)
    glob_files("D:/過去の研究データ/2023sheetsHands/tokuyama/right/omote", 17)
    glob_files("D:/過去の研究データ/2023sheetsHands/watanabe/right/omote", 18)
    glob_files("D:/過去の研究データ/2023sheetsHands/yamaguchi/right/omote", 19)
    np.savez(outfile, x = x, y = y)
    print("保存しました:" + outfile, len(x))
    print(x[0], y[0])
    
def glob_files(path, label):
    files = glob.glob(path + "/*.jpg")
    random.shuffle(files)
    num = 0
    for f in files:
        if num >= len(files): break
        num += 1

        #---------edgesの時のプログラム--------------
        img = cv2.imread(f)
        img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        karnel = np.array(laplace5 , np.float64)
        edges=cv2.filter2D(img_gray, -1, karnel)
        #画像のリサイズ処理
        result_img = cv2.resize(edges, (photo_size, photo_size)) 

        #1つの配列に格納（この場合2つ）
        result_img = np.asarray(result_img) 
        x.append(result_img) 
        y.append(label) 
        
if __name__ == '__main__':
    main()

保存しました:D:/過去の研究データ/2023npz/2023UsingFrontAndBackHands/separateLearn/100sheetsNum20FrontEdgesKarnel5-128pix.npz 2000
[[ 12   0   0 ...  20   0  11]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [255 245 255 ... 104 255 255]] 0


In [2]:
import numpy as np
from PIL import Image
import cv2
import glob, random
%matplotlib inline

#変更必要
outfile = "D:/過去の研究データ/2023npz/2023UsingFrontAndBackHands/separateLearn/100sheetsNum20BackEdgesKarnel5-128pix.npz"
#変更必要
photo_size = 128
x = []
y = []
laplace5 = [[-1, -3, -4, -3, -1],
           [-3, 0, 6, 0, -3],
           [-4, 6, 20, 6, -4],
           [-3, 0, 6, 0, -3],
           [-1, -3, -4, -3, -1]]

def main():
    glob_files("D:/過去の研究データ/2023sheetsHands/aizawa/right/ura", 0)
    glob_files("D:/過去の研究データ/2023sheetsHands/arai/right/ura", 1)
    glob_files("D:/過去の研究データ/2023sheetsHands/ebato/right/ura", 2)
    glob_files("D:/過去の研究データ/2023sheetsHands/hasegawa/right/ura", 3)
    glob_files("D:/過去の研究データ/2023sheetsHands/higuchi/right/ura", 4)
    glob_files("D:/過去の研究データ/2023sheetsHands/isii/right/ura", 5)
    glob_files("D:/過去の研究データ/2023sheetsHands/kojima/right/ura", 6)
    glob_files("D:/過去の研究データ/2023sheetsHands/nakamura/right/ura", 7)
    glob_files("D:/過去の研究データ/2023sheetsHands/oono/right/ura", 8)
    glob_files("D:/過去の研究データ/2023sheetsHands/sakai/right/ura", 9)
    glob_files("D:/過去の研究データ/2023sheetsHands/sekine/right/ura", 10)
    glob_files("D:/過去の研究データ/2023sheetsHands/shimada/right/ura", 11)
    glob_files("D:/過去の研究データ/2023sheetsHands/shimizu/right/ura", 12)
    glob_files("D:/過去の研究データ/2023sheetsHands/takahashi/right/ura", 13)
    glob_files("D:/過去の研究データ/2023sheetsHands/tanakahiroki/right/ura", 14)
    glob_files("D:/過去の研究データ/2023sheetsHands/tanakamiyu/right/ura", 15)
    glob_files("D:/過去の研究データ/2023sheetsHands/tanakataiki/right/ura", 16)
    glob_files("D:/過去の研究データ/2023sheetsHands/tokuyama/right/ura", 17)
    glob_files("D:/過去の研究データ/2023sheetsHands/watanabe/right/ura", 18)
    glob_files("D:/過去の研究データ/2023sheetsHands/yamaguchi/right/ura", 19)
    np.savez(outfile, x = x, y = y)
    print("保存しました:" + outfile, len(x))
    print(x[0], y[0])
    
def glob_files(path, label):
    files = glob.glob(path + "/*.jpg")
    random.shuffle(files)
    num = 0
    for f in files:
        if num >= len(files): break
        num += 1

        #---------edgesの時のプログラム--------------
        img = cv2.imread(f)
        img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        karnel = np.array(laplace5 , np.float64)
        edges=cv2.filter2D(img_gray, -1, karnel)
        #画像のリサイズ処理
        result_img = cv2.resize(edges, (photo_size, photo_size)) 

        #1つの配列に格納（この場合2つ）
        result_img = np.asarray(result_img) 
        x.append(result_img) 
        y.append(label) 
        
if __name__ == '__main__':
    main()

保存しました:D:/過去の研究データ/2023npz/2023UsingFrontAndBackHands/separateLearn/100sheetsNum20BackEdgesKarnel5-128pix.npz 2000
[[  0   0   8 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   2   0   0]
 [  0   0   0 ...   0  17   7]
 [255 243 255 ...   0   0   0]] 0


In [8]:
%%time
import keras 
from keras.models import Sequential
from keras.layers import Dense,Dropout,Flatten
from keras.layers import Conv2D,MaxPooling2D
from keras.optimizers import RMSprop
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np


def def_model(in_shape, nb_classes):
    model = Sequential()
    model.add(Conv2D(32,
              kernel_size = (3, 3),
              activation = 'relu',
              input_shape = in_shape))
    model.add(Conv2D(32, (3, 3), activation = 'relu'))
    model.add(MaxPooling2D(pool_size = (2, 2)))
    model.add(Dropout(0.25))

    model.add(Conv2D(64, (3, 3), activation = 'relu'))
    model.add(Conv2D(64, (3, 3), activation = 'relu'))
    model.add(MaxPooling2D(pool_size = (2, 2)))
    model.add(Dropout(0.25))

    model.add(Flatten())
    model.add(Dense(512, activation = 'relu'))
    model.add(Dropout(0.5))
    model.add(Dense(nb_classes, activation = 'softmax'))
    model.summary()
    return model

def get_model(in_shape, nb_classes):
    model = def_model(in_shape, nb_classes)
    model.compile(
        loss = 'categorical_crossentropy',
        optimizer = RMSprop(),
        metrics = ['accuracy'])
    return model

# 変更必要
im_size = 128
im_color = 1
in_shape = (im_size, im_size, im_color)
nb_classes = 20
hands = "Back"
batch = 256

#変更必要
photos = np.load('D:/過去の研究データ/2023npz/2023UsingFrontAndBackHands/separateLearn/100sheetsNum20' + hands + 'EdgesKarnel5-' + str(im_size) + 'pix.npz')
x = photos['x']
y = photos['y']

x = x.reshape(-1, im_size, im_size, im_color)
x = x.astype('float32') / 255
y = keras.utils.to_categorical(y.astype('int32'), nb_classes)

x_train, x_test, y_train, y_test = train_test_split(
    x, y, train_size = 0.9)

model = get_model(in_shape, nb_classes)


hist = model.fit(x_train, y_train,
          batch_size = batch, 
          epochs = 20,
          verbose = 1,
          validation_data = (x_test, y_test))

score = model.evaluate(x_test, y_test, verbose = 1)
print('正解率=', score[1], 'loss=', score[0])

plt.plot(hist.history['accuracy'])
plt.plot(hist.history['val_accuracy'])
plt.title('Accuracy')
plt.legend(['train', 'test'], loc = 'upper left')
plt.show()

plt.plot(hist.history['loss'])
plt.plot(hist.history['val_loss'])
plt.title('Loss')
plt.legend(['train', 'test'], loc = 'upper left')
plt.show()

#変更必要
model.save_weights('D:/過去の研究データ/2023hdf/2023separateLearn/100sheetsNum20' + hands + 'EdgesKarnel5-' + str(im_size) + 'pixBatch' + str(batch) + '.hdf5') 

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_28 (Conv2D)          (None, 126, 126, 32)      320       
                                                                 
 conv2d_29 (Conv2D)          (None, 124, 124, 32)      9248      
                                                                 
 max_pooling2d_14 (MaxPoolin  (None, 62, 62, 32)       0         
 g2D)                                                            
                                                                 
 dropout_21 (Dropout)        (None, 62, 62, 32)        0         
                                                                 
 conv2d_30 (Conv2D)          (None, 60, 60, 64)        18496     
                                                                 
 conv2d_31 (Conv2D)          (None, 58, 58, 64)        36928     
                                                      

Wall time: 14min 12s


In [37]:
#他人受入率評価用のプログラム 
import keras 
from keras.models import Sequential
from keras.layers import Dense,Dropout,Flatten
from keras.layers import Conv2D,MaxPooling2D
from keras.optimizers import RMSprop
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
import cv2
from PIL import Image


def def_model(in_shape, nb_classes):
    model = Sequential()
    model.add(Conv2D(32,
              kernel_size = (3, 3),
              activation = 'relu',
              input_shape = in_shape))
    model.add(Conv2D(32, (3, 3), activation = 'relu'))
    model.add(MaxPooling2D(pool_size = (2, 2)))
    model.add(Dropout(0.25))

    model.add(Conv2D(64, (3, 3), activation = 'relu'))
    model.add(Conv2D(64, (3, 3), activation = 'relu'))
    model.add(MaxPooling2D(pool_size = (2, 2)))
    model.add(Dropout(0.25))

    model.add(Flatten())
    model.add(Dense(512, activation = 'relu'))
    model.add(Dropout(0.5))
    model.add(Dense(nb_classes, activation = 'softmax'))
    return model


def get_model(in_shape, nb_classes):
    model = def_model(in_shape, nb_classes)
    model.compile(
        loss = 'categorical_crossentropy',
        optimizer = RMSprop(),
        metrics = ['accuracy'])
    return model

#他人受入率用のテスト配列
omote = ["gotou/omote",
        "isii/omote",
        "mimura/omote",
        "nakamura/omote",
        "okutani/omote",
        "saitouhide/omote",
        "saitouryou/omote",
        "sakuma/omote",
        "tanaka/omote",
        "tochikubo/omote"]
ura = ["gotou/ura",
     "isii/ura",
     "mimura/ura",
     "nakamura/ura",
     "okutani/ura",
     "saitouhide/ura",
     "saitouryou/ura",
     "sakuma/ura",
     "tanaka/ura",
     "tochikubo/ura"]

laplace5 = [[-1, -3, -4, -3, -1],
           [-3, 0, 6, 0, -3],
           [-4, 6, 20, 6, -4],
           [-3, 0, 6, 0, -3],
           [-1, -3, -4, -3, -1]]
#表の評価画像と裏の評価画像のパスが格納
target_omote = []
target_ura = []
#誤って他人を受入れてしまった確率が格納
passpercent = []
#正しく他人を拒否した確率が格納
notpasspercent = []
#閾値以上で受入れられた確率が表と裏でそれぞれ格納-----追加1
omotePassPercent = []
uraPassPercent = []
#閾値未満ではじかれた確率が表と裏でそれぞれ格納
omoteNotPercent = []
uraNotPercent = []

#target_omoteに表の画像を入れ、target_uraに裏の画像を入れる
#変更必要
for k in range(10):
    for i in range(10):
        target_omote.append("D:/過去の研究データ/graytest/" + str(omote[k]) + "/" + str(i) + ".jpg")
        target_ura.append("D:/過去の研究データ/graytest/" + str(ura[k]) + "/" + str(i) + ".jpg")
        
#変更必要
im_size = 128
im_color = 1
in_shape = (im_size, im_size, im_color)
nb_classes = 20
#配列の最大値
max_score = 0.0
min_score = 0.0
#閾値の設定-----追加2
omote_thresh = 91.8
ura_thresh = 88.5
batch = "256"

LABELS_Front = ["相澤さんの表", "新井さんの表",
                "江波戸の表", "長谷川さんの表",
                "樋口さんの表", "石井さんの表",
                "小島さんの表", "中村さんの表",
                "大野さんの表", "坂井さんの表",
                "関根さんの表", "島田さんの表",
                "清水さんの表", "高橋さんの表",
                "田中ひろきさんの表", "田中みゆさんの表",
                "田中たいきさんの表", "徳山さんの表",
                "渡邉さんの表", "山口さんの表",]
LABELS_Back = ["相澤さんの裏", "新井さんの裏",
                "江波戸の裏", "長谷川さんの裏",
                "樋口さんの裏", "石井さんの裏",
                "小島さんの裏", "中村さんの裏",
                "大野さんの裏", "坂井さんの裏",
                "関根さんの裏", "島田さんの裏",
                "清水さんの裏", "高橋さんの裏",
                "田中ひろきさんの裏", "田中みゆさんの裏",
                "田中たいきさんの裏", "徳山さんの裏",
                "渡邉さんの裏", "山口さんの裏"]

model_front = get_model(in_shape, nb_classes)
model_back = get_model(in_shape, nb_classes)
#変更必要
# model_front.load_weights('D:/過去の研究データ/2023hdf/2023separateLearn/2023Num20FrontEdgesKarnel5-' + str(im_size) + 'pixBatch' + batch + '.hdf5')
# model_back.load_weights('D:/過去の研究データ/2023hdf/2023separateLearn/2023Num20BackEdgesKarnel5-' + str(im_size) + 'pixBatch' + batch + '.hdf5')
model_front.load_weights('D:/過去の研究データ/2023hdf/2023separateLearn/100sheetsNum20FrontEdgesKarnel5-' + str(im_size) + 'pixBatch' + batch + '.hdf5')
model_back.load_weights('D:/過去の研究データ/2023hdf/2023separateLearn/100sheetsNum20BackEdgesKarnel5-' + str(im_size) + 'pixBatch' + batch + '.hdf5')

#評価画像の確率を受け取り、max_scoreよりも大きい値をmax_scoreとして更新する
def findmaxscore(per):
    global max_score
    if per != 100.0:
        if max_score <= per:
            max_score = per 

def findminscore(per):
    global min_score
    if per != 100.0:
        if min_score <= per:
            min_score = per 
            
def check_photo(path):
    img = cv2.imread(path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    karnel = np.array(laplace5, np.float64)
    img = cv2.filter2D(img, -1, karnel)
    #画像のリサイズ
    result_img = cv2.resize(img, (im_size, im_size)) 
    # plt.imshow(result_img, cmap = 'gray')
    # plt.show()

    x = np.asarray(result_img)
    x = x.reshape(-1, im_size, im_size, im_color)
    x = x / 255
    
    #画像の予測
    if "/omote" in path:
        pre = model_front.predict([x])[0]
    elif "/ura" in path:
        pre = model_back.predict([x])[0]
    idx = pre.argmax()
    per = (pre[idx] * 100)
    #閾値(この段階では認証はしないが閾値未満の画像を格納する)
    if per < omote_thresh and ("/omote" in path): 
        omoteNotPercent.append(per)
    elif per < ura_thresh and ("/ura" in path):
        uraNotPercent.append(per)
    else:
        pass
    return (idx, per)

def check_photo_str(path_omote, path_ura):
    idx_omote, per_omote = check_photo(path_omote)
    idx_ura, per_ura = check_photo(path_ura)
    #Aさんの表を「Aさん」と「表」に分割する
    omotePerson = LABELS_Front[idx_omote].split("の")
    uraPerson = LABELS_Back[idx_ura].split("の")
    #表の評価画像と裏の評価画像が閾値以上かつ人の名前が一致しているかつ表裏の評価画像が表と裏で一致しているかの判定
    if per_omote >= omote_thresh and per_ura >= ura_thresh and omotePerson[0] == uraPerson[0] and omotePerson[1] == "表" and uraPerson[1] == "裏":
        print("この手は表:", LABELS_Front[idx_omote], "裏:", LABELS_Back[idx_ura], "です")
        print("可能性は表の手:", per_omote, "%", "裏の手:", per_ura, "%なので認証します")
        
        #誤って他人を受入れてしまった確率を配列に格納
        passpercent.append(per_omote)
        passpercent.append(per_ura)
        omotePassPercent.append(per_omote)#-----追加3
        uraPassPercent.append(per_ura)
        
        #max_scoreよりも大きい確率かどうかを判定する
        findmaxscore(per_omote)
        findmaxscore(per_ura)
        
    else:
        print('\033[31m' + "可能性が表の手:", per_omote, "% 裏の手:", per_ura, "%なので認証できません" + '\033[0m')
        print('\033[31m' + "認証の結果は表の手:", LABELS_Front[idx_omote], " 裏の手:", LABELS_Back[idx_ura], "でした" + '\033[0m')
        #正しく他人を拒否した確率を配列に格納する
        notpasspercent.append(per_omote)
        notpasspercent.append(per_ura)

        findminscore(per_omote)
        findminscore(per_ura)
    
if __name__ == '__main__':
    for i in range(100):
        print("\nここからは" + str(i) + "番目の写真です")
        #表と裏の評価画像を渡して認証を行う
        check_photo_str(target_omote[i], target_ura[i])
        if i % 10 == 9:
            print("================================================")
            print("テスト対象の人が変わります")
            print("================================================")
    #他人受入率の配列の中身を表示
    print(omotePassPercent)#-----追加4
    print(uraPassPercent)
    #他人拒否率の配列の中身を表示
    print(omoteNotPercent)
    print(uraNotPercent)
    print("エッジ画像カーネル5 " + str(im_size) + "px バッチサイズ" + str(batch))
    print("他人受入に用いる個数" + str(len(passpercent)))
    #全体の他人受入率算出用に変数FARに他人受入の個数を格納
    FAR = len(passpercent)
    print("閾値未満で識別したテスト数" + str(len(notpasspercent)))
    print("表の手だけで閾値未満で識別したテスト数" + str(len(omoteNotPercent)))
    print("裏の手だけで閾値未満で識別したテスト数" + str(len(uraNotPercent)))
    #表裏合計、それぞれの他人受入(拒否)率を算出する
    totalpass = len(passpercent) / 200
    totalnotpass = len(notpasspercent) / 200
    omotenotpass = len(omoteNotPercent) / 100
    omotepass = (100 - len(omoteNotPercent)) / 100
    uranotpass = len(uraNotPercent) / 100
    urapass = (100 - len(uraNotPercent)) / 100
    print("================================================")
    #未学習の手を閾値未満で識別した割合
    print("他人拒否率" + str(round(totalnotpass * 100, 4)) + "%")
    #未学習の手を閾値以上で識別した割合
    print("他人受入率" + str(round(totalpass * 100, 4)) + "%")
    # print("表の手だけで未学習の手を閾値未満で識別した割合" + str(round(omotenotpass * 100, 4)) + "%")
    # print("表の手だけで未学習の手を閾値以上で識別した割合" + str(round(omotepass * 100, 4)) + "%")
    # print("裏の手だけで未学習の手を閾値未満で識別した割合" + str(round(uranotpass * 100, 4)) + "%")
    # print("裏の手だけで未学習の手を閾値以上で識別した割合" + str(round(urapass * 100, 4)) + "%")
    print("表の手で閾値未満の最大値は" + str(max(omoteNotPercent)))#-----追加5
    print("裏の手で閾値未満の最大値は" + str(max(uraNotPercent)))
    print("表の平均値"+ str(np.mean(omoteNotPercent)))
    print("裏の平均値"+ str(np.mean(uraNotPercent)))
    try:
        print("表の手で閾値以上の最小値は" + str(min(omotePassPercent)))#-----追加6
        print("裏の手で閾値以上の最小値は" + str(min(uraPassPercent)))
    except:
        pass


ここからは0番目の写真です
1/1 [==============================] - 0s 64ms/step
可能性が表の手: 91.81745648384094 % 裏の手: 40.42744040489197 %なので認証できません
認証の結果は表の手: 高橋さんの表  裏の手: 田中ひろきさんの裏 でした

ここからは1番目の写真です
1/1 [==============================] - 0s 25ms/step
可能性が表の手: 57.88169503211975 % 裏の手: 31.376570463180542 %なので認証できません
認証の結果は表の手: 高橋さんの表  裏の手: 島田さんの裏 でした

ここからは2番目の写真です
1/1 [==============================] - 0s 24ms/step
可能性が表の手: 45.22135257720947 % 裏の手: 36.745744943618774 %なので認証できません
認証の結果は表の手: 高橋さんの表  裏の手: 島田さんの裏 でした

ここからは3番目の写真です
1/1 [==============================] - 0s 26ms/step
可能性が表の手: 65.00502824783325 % 裏の手: 63.81973624229431 %なので認証できません
認証の結果は表の手: 高橋さんの表  裏の手: 島田さんの裏 でした

ここからは4番目の写真です
1/1 [==============================] - 0s 24ms/step
可能性が表の手: 80.39018511772156 % 裏の手: 86.65522336959839 %なので認証できません
認証の結果は表の手: 関根さんの表  裏の手: 島田さんの裏 でした

ここからは5番目の写真です
1/1 [==============================] - 0s 28ms/step
可能性が表の手: 80.85828423500061 % 裏の手: 63.39446306228638 %なので認証できません
認証の結果は表の手: 関根さんの表  裏の手: 島田さんの裏 でした

In [38]:
#本人受入率評価用のプログラム
import math
import keras 
from keras.models import Sequential
from keras.layers import Dense,Dropout,Flatten
from keras.layers import Conv2D,MaxPooling2D
from keras.optimizers import RMSprop
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image


def def_model(in_shape, nb_classes):
    model = Sequential()
    model.add(Conv2D(32,
              kernel_size = (3, 3),
              activation = 'relu',
              input_shape = in_shape))
    model.add(Conv2D(32, (3, 3), activation = 'relu'))
    model.add(MaxPooling2D(pool_size = (2, 2)))
    model.add(Dropout(0.25))

    model.add(Conv2D(64, (3, 3), activation = 'relu'))
    model.add(Conv2D(64, (3, 3), activation = 'relu'))
    model.add(MaxPooling2D(pool_size = (2, 2)))
    model.add(Dropout(0.25))

    model.add(Flatten())
    model.add(Dense(512, activation = 'relu'))
    model.add(Dropout(0.5))
    model.add(Dense(nb_classes, activation = 'softmax'))
    return model


def get_model(in_shape, nb_classes):
    model = def_model(in_shape, nb_classes)
    model.compile(
        loss = 'categorical_crossentropy',
        optimizer = RMSprop(),
        metrics = ['accuracy'])
    return model

#学習済みの人の評価画像
omote = ["aizawa/right/omote",
        "arai/right/omote",
        "ebato/right/omote",
        "hasegawa/right/omote",
        "higuchi/right/omote",
        "isii/right/omote",
        "kojima/right/omote",
        "nakamura/right/omote",
        "oono/right/omote",
        "sakai/right/omote",
        "sekine/right/omote",
        "shimada/right/omote",
        "shimizu/right/omote",
        "takahashi/right/omote",
        "tanakahiroki/right/omote",
        "tanakamiyu/right/omote",
        "tanakataiki/right/omote",
        "tokuyama/right/omote",
        "watanabe/right/omote",
        "yamaguchi/right/omote"]
ura = ["aizawa/right/ura",
        "arai/right/ura",
        "ebato/right/ura",
        "hasegawa/right/ura",
        "higuchi/right/ura",
        "isii/right/ura",
        "kojima/right/ura",
        "nakamura/right/ura",
        "oono/right/ura",
        "sakai/right/ura",
        "sekine/right/ura",
        "shimada/right/ura",
        "shimizu/right/ura",
        "takahashi/right/ura",
        "tanakahiroki/right/ura",
        "tanakamiyu/right/ura",
        "tanakataiki/right/ura",
        "tokuyama/right/ura",
        "watanabe/right/ura",
        "yamaguchi/right/ura"]

laplace5 = [[-1, -3, -4, -3, -1],
           [-3, 0, 6, 0, -3],
           [-4, 6, 20, 6, -4],
           [-3, 0, 6, 0, -3],
           [-1, -3, -4, -3, -1]]
#表の評価画像と裏の評価画像のパスが格納
target_omote = []
target_ura = []
#誤って他人を受入れてしまった確率が格納
passpercent = []
#正しく他人を拒否した確率が格納
notpasspercent = []
#閾値未満ではじかれた確率が表と裏でそれぞれ格納
omoteNotPercent = []
uraNotPercent = []
#閾値以上で受入れられた確率が表と裏でそれぞれ格納-----追加1
omotePassPercent = []
uraPassPercent = []
#学習済みの人の中で他人を受入れた場合の警告表示が格納
notIncludeLABEL = []

#変更必要
for k in range(20):
    for i in range(10):
        target_omote.append("D:/過去の研究データ/2023graytest/" + str(omote[k]) + "/gray" + str(i) + ".jpg")
        target_ura.append("D:/過去の研究データ/2023graytest/" + str(ura[k]) + "/gray" + str(i) + ".jpg")

#変更必要
im_size = 128
im_color = 1
in_shape = (im_size, im_size, im_color)
nb_classes = 20
#配列の最大値
max_score = 0.0
#閾値の設定-----追加2
omote_thresh = 91.8
ura_thresh = 88.5
batch = "256"

#学習した人のラベル
LABELS_Front = ["相澤さんの表", "新井さんの表",
                "江波戸の表", "長谷川さんの表",
                "樋口さんの表", "石井さんの表",
                "小島さんの表", "中村さんの表",
                "大野さんの表", "坂井さんの表",
                "関根さんの表", "島田さんの表",
                "清水さんの表", "高橋さんの表",
                "田中ひろきさんの表", "田中みゆさんの表",
                "田中たいきさんの表", "徳山さんの表",
                "渡邉さんの表", "山口さんの表",]
LABELS_Back = ["相澤さんの裏", "新井さんの裏",
                "江波戸の裏", "長谷川さんの裏",
                "樋口さんの裏", "石井さんの裏",
                "小島さんの裏", "中村さんの裏",
                "大野さんの裏", "坂井さんの裏",
                "関根さんの裏", "島田さんの裏",
                "清水さんの裏", "高橋さんの裏",
                "田中ひろきさんの裏", "田中みゆさんの裏",
                "田中たいきさんの裏", "徳山さんの裏",
                "渡邉さんの裏", "山口さんの裏"]
#確定ラベル
AbsLABELS = ["相澤さん", "新井さん", "江波戸", "長谷川さん",
             "樋口さん", "石井さん", "小島さん", "中村さん",
             "大野さん", "坂井さん", "関根さん", "島田さん",
             "清水さん", "高橋さん", "田中ひろきさん", "田中みゆさん",
             "田中たいきさん", "徳山さん", "渡邉さん",  "山口さん"]

model_front = get_model(in_shape, nb_classes)
model_back = get_model(in_shape, nb_classes)
#変更必要
# model_front.load_weights('D:/過去の研究データ/2023hdf/2023separateLearn/2023Num20FrontEdgesKarnel5-' + str(im_size) + 'pixBatch' + batch + '.hdf5')
# model_back.load_weights('D:/過去の研究データ/2023hdf/2023separateLearn/2023Num20BackEdgesKarnel5-' + str(im_size) + 'pixBatch' + batch + '.hdf5')
model_front.load_weights('D:/過去の研究データ/2023hdf/2023separateLearn/100sheetsNum20FrontEdgesKarnel5-' + str(im_size) + 'pixBatch' + batch + '.hdf5')
model_back.load_weights('D:/過去の研究データ/2023hdf/2023separateLearn/100sheetsNum20BackEdgesKarnel5-' + str(im_size) + 'pixBatch' + batch + '.hdf5')

#評価画像の確率を受け取り、max_scoreよりも大きい値をmax_scoreとして更新する
def findmaxscore(per):
    global max_score
    if per != 100.0:
        if max_score <= per:
            max_score = per
                
def check_photo(path):
    img = cv2.imread(path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    karnel = np.array(laplace5, np.float64)
    img = cv2.filter2D(img, -1, karnel)
    #画像のリサイズ
    result_img = cv2.resize(img, (im_size, im_size))
    #画像の表示
    # plt.imshow(result_img, cmap = 'gray')
    # plt.show()

    x = np.asarray(result_img)
    x = x.reshape(-1, im_size, im_size, im_color)
    x = x / 255
    
    #画像の予測
    if "/omote" in path:
        pre = model_front.predict([x])[0]
    elif "/ura" in path:
        pre = model_back.predict([x])[0]
    idx = pre.argmax()
    per = (pre[idx] * 100)
    #閾値(この段階では認証はしないが閾値未満の画像を格納する)
    if per < omote_thresh and ("/omote" in path):
        omoteNotPercent.append(per)
    elif per < ura_thresh and ("/ura" in path):
        uraNotPercent.append(per)
    else:
        pass
    return(idx, per)

def check_photo_str(path_omote, path_ura, i): 
    idx_omote, per_omote = check_photo(path_omote)
    idx_ura, per_ura = check_photo(path_ura)
    #Aさんの表を「Aさん」と「表」に分割する
    omotePerson = LABELS_Front[idx_omote].split("の")
    uraPerson = LABELS_Back[idx_ura].split("の")
    #表の評価画像と裏の評価画像が閾値以上かつ人の名前が一致しているかつ表裏の評価画像が表と裏で一致しているかの判定
    if per_omote >= omote_thresh and per_ura >= ura_thresh and omotePerson[0] == uraPerson[0] and omotePerson[1] == "表" and uraPerson[1] == "裏":
        print("この手は表:", LABELS_Front[idx_omote], "裏:", LABELS_Back[idx_ura], "です")
        print("可能性は表の手:", per_omote, "%", "裏の手:", per_ura, "%なので認証します")
        #上記条件を満たしたのに識別を間違えているときの処理
        if i < 10:
            ConfLABEL = AbsLABELS[0]
        elif i < 20:
            ConfLABEL = AbsLABELS[1]
        elif i < 30:
            ConfLABEL = AbsLABELS[2]
        elif i < 40:
            ConfLABEL = AbsLABELS[3]
        elif i < 50:
            ConfLABEL = AbsLABELS[4]
        elif i < 60:
            ConfLABEL = AbsLABELS[5]
        elif i < 70:
            ConfLABEL = AbsLABELS[6]
        elif i < 80:
            ConfLABEL = AbsLABELS[7]
        elif i < 90:
            ConfLABEL = AbsLABELS[8]
        elif i < 100:
            ConfLABEL = AbsLABELS[9]
        elif i < 110:
            ConfLABEL = AbsLABELS[10]
        elif i < 120:
            ConfLABEL = AbsLABELS[11]
        elif i < 130:
            ConfLABEL = AbsLABELS[12]
        elif i < 140:
            ConfLABEL = AbsLABELS[13]
        elif i < 150:
            ConfLABEL = AbsLABELS[14]
        elif i < 160:
            ConfLABEL = AbsLABELS[15]
        elif i < 170:
            ConfLABEL = AbsLABELS[16]
        elif i < 180:
            ConfLABEL = AbsLABELS[17]
        elif i < 190:
            ConfLABEL = AbsLABELS[18]
        elif i < 200:
            ConfLABEL = AbsLABELS[19]

        if ConfLABEL not in LABELS_Front[idx_omote] :
            notIncludeLABEL.append("-" + ConfLABEL + "を" + LABELS_Front[idx_omote] + "だと誤認識-")  
            print('\033[31m' + '識別エラーが起きています' + '\033[0m')
        if ConfLABEL not in LABELS_Back[idx_ura]:
            notIncludeLABEL.append("-" + ConfLABEL + "を" + LABELS_Back[idx_ura] + "だと誤認識-")  
            print('\033[31m' + '識別エラーが起きています' + '\033[0m')

        #本人受入の配列に格納
        passpercent.append(per_omote)
        passpercent.append(per_ura)
        omotePassPercent.append(per_omote)#-----追加3
        uraPassPercent.append(per_ura)
        
        #max_scoreよりも大きい確率かどうかを判定する
        findmaxscore(per_omote)
        findmaxscore(per_ura)
        
    else:
        print('\033[31m' + "可能性が表の手:", per_omote, "% 裏の手:", per_ura, "%なので認証できません" + '\033[0m')
        print('\033[31m' + "認証の結果は表の手:", LABELS_Front[idx_omote], " 裏の手:", LABELS_Back[idx_ura], "でした" + '\033[0m')
        #誤って本人を拒否してしまった人の確率を配列に格納
        notpasspercent.append(per_omote)
        notpasspercent.append(per_ura)
    
if __name__ == '__main__':
    #学習人数が増えたらiのrangeを変更必要
    for i in range(200): 
        print("\nここからは" + str(i) + "番目の写真です")
        #表と裏の評価画像を渡して認証を行う
        check_photo_str(target_omote[i], target_ura[i], i)
        if i % 10 == 9:
            print("================================================")
            print("テスト対象の人が変わります")
            print("================================================")
    #本人受入率の配列の中身を表示
    print(omotePassPercent)#-----追加4
    print(uraPassPercent)
    #本人拒否率の配列の中身を表示
    print(omoteNotPercent)
    print(uraNotPercent)
    print("----------------------------------------------------------------")   
    print("閾値以上で識別したテスト数" + str(len(passpercent)))
    print("閾値未満で識別したテスト数" + str(len(notpasspercent)))
    print("表の手だけで閾値未満で識別したテスト数" + str(len(omoteNotPercent)))
    print("裏の手だけで閾値未満で識別したテスト数" + str(len(uraNotPercent)))
    totalpass = len(passpercent) / 400
    totalnotpass = len(notpasspercent) / 400
    omotenotpass = len(omoteNotPercent) / 200
    omotepass = (200 - len(omoteNotPercent)) / 200
    uranotpass = len(uraNotPercent) / 200
    urapass = (200 - len(uraNotPercent)) / 200
    print("================================================")
    #学習済みの人の手を閾値未満で識別した割合
    print("本人拒否率" + str(round(totalnotpass * 100, 4)) + "%")
    #学習済みの人の手を閾値以上で識別した割合
    print("本人受入率" + str(round(totalpass * 100, 4)) + "%")
    # print("表の手だけを閾値未満で識別した割合" + str(round(omotenotpass * 100, 4)) + "%")
    # print("表の手だけを閾値以上で識別した割合" + str(round(omotepass * 100, 4)) + "%")
    # print("裏の手だけを閾値未満で識別した割合" + str(round(uranotpass * 100, 4)) + "%")
    # print("裏の手だけを閾値以上で識別した割合" + str(round(urapass * 100, 4)) + "%")
    try:
        print("表の手で閾値未満の最大値は" + str(max(omoteNotPercent)))#-----追加5
        print("裏の手で閾値未満の最大値は" + str(max(uraNotPercent)))
        print("表の平均値"+ str(np.mean(omoteNotPercent)))
        print("裏の平均値"+ str(np.mean(uraNotPercent)))
    except:
        pass
    try:
        print("表の手で閾値以上の最小値は" + str(min(omotePassPercent)))#-----追加6
        print("裏の手で閾値以上の最小値は" + str(min(uraPassPercent)))
    except:
        pass
    #他人受入率の評価と本人拒否率の評価すべてにおける他人受入
    print(notIncludeLABEL)
    print("全体の他人受入率は" + str(round((FAR + len(notIncludeLABEL)) / 600 * 100, 4)) + "%")
    #他人受入率の算出時に受け入れてしまった個数
    print(FAR)
    #学習済みの人の手の中で他人を受入れてしまった人の個数
    print(len(notIncludeLABEL))


ここからは0番目の写真です
1/1 [==============================] - 0s 69ms/step
この手は表: 相澤さんの表 裏: 相澤さんの裏 です
可能性は表の手: 99.99798536300659 % 裏の手: 99.9873161315918 %なので認証します

ここからは1番目の写真です
1/1 [==============================] - 0s 27ms/step
この手は表: 相澤さんの表 裏: 相澤さんの裏 です
可能性は表の手: 99.99641180038452 % 裏の手: 99.99462366104126 %なので認証します

ここからは2番目の写真です
1/1 [==============================] - 0s 25ms/step
この手は表: 相澤さんの表 裏: 相澤さんの裏 です
可能性は表の手: 99.99995231628418 % 裏の手: 99.99983310699463 %なので認証します

ここからは3番目の写真です
1/1 [==============================] - 0s 26ms/step
この手は表: 相澤さんの表 裏: 相澤さんの裏 です
可能性は表の手: 99.99984502792358 % 裏の手: 99.99960660934448 %なので認証します

ここからは4番目の写真です
1/1 [==============================] - 0s 27ms/step
この手は表: 相澤さんの表 裏: 相澤さんの裏 です
可能性は表の手: 99.9998688697815 % 裏の手: 99.99949932098389 %なので認証します

ここからは5番目の写真です
1/1 [==============================] - 0s 27ms/step
可能性が表の手: 79.42038178443909 % 裏の手: 99.9971866607666 %なので認証できません
認証の結果は表の手: 相澤さんの表  裏の手: 相澤さんの裏 でした

ここからは6番目の写真です
1/1 [==============================] - 0s 

In [23]:
#他人受入率評価用のプログラム(閾値を用いずに認証)
import keras 
from keras.models import Sequential
from keras.layers import Dense,Dropout,Flatten
from keras.layers import Conv2D,MaxPooling2D
from keras.optimizers import RMSprop
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
import cv2
from PIL import Image


def def_model(in_shape, nb_classes):
    model = Sequential()
    model.add(Conv2D(32,
              kernel_size = (3, 3),
              activation = 'relu',
              input_shape = in_shape))
    model.add(Conv2D(32, (3, 3), activation = 'relu'))
    model.add(MaxPooling2D(pool_size = (2, 2)))
    model.add(Dropout(0.25))

    model.add(Conv2D(64, (3, 3), activation = 'relu'))
    model.add(Conv2D(64, (3, 3), activation = 'relu'))
    model.add(MaxPooling2D(pool_size = (2, 2)))
    model.add(Dropout(0.25))

    model.add(Flatten())
    model.add(Dense(512, activation = 'relu'))
    model.add(Dropout(0.5))
    model.add(Dense(nb_classes, activation = 'softmax'))
    return model


def get_model(in_shape, nb_classes):
    model = def_model(in_shape, nb_classes)
    model.compile(
        loss = 'categorical_crossentropy',
        optimizer = RMSprop(),
        metrics = ['accuracy'])
    return model

#他人受入率用のテスト配列
omote = ["gotou/omote",
        "isii/omote",
        "mimura/omote",
        "nakamura/omote",
        "okutani/omote",
        "saitouhide/omote",
        "saitouryou/omote",
        "sakuma/omote",
        "tanaka/omote",
        "tochikubo/omote"]
ura = ["gotou/ura",
     "isii/ura",
     "mimura/ura",
     "nakamura/ura",
     "okutani/ura",
     "saitouhide/ura",
     "saitouryou/ura",
     "sakuma/ura",
     "tanaka/ura",
     "tochikubo/ura"]

laplace5 = [[-1, -3, -4, -3, -1],
           [-3, 0, 6, 0, -3],
           [-4, 6, 20, 6, -4],
           [-3, 0, 6, 0, -3],
           [-1, -3, -4, -3, -1]]
#表の評価画像と裏の評価画像のパスが格納
target_omote = []
target_ura = []
#誤って他人を受入れてしまった確率が格納
passpercent = []
#正しく他人を拒否した確率が格納
notpasspercent = []

#target_omoteに表の画像を入れ、target_uraに裏の画像を入れる
#変更必要
for k in range(10):
    for i in range(10):
        target_omote.append("D:/過去の研究データ/graytest/" + str(omote[k]) + "/" + str(i) + ".jpg")
        target_ura.append("D:/過去の研究データ/graytest/" + str(ura[k]) + "/" + str(i) + ".jpg")
        
#変更必要
im_size = 128
im_color = 1
in_shape = (im_size, im_size, im_color)
nb_classes = 20
#配列の最大値
max_score = 0.0
batch = "256"

LABELS_Front = ["相澤さんの表", "新井さんの表",
                "江波戸の表", "長谷川さんの表",
                "樋口さんの表", "石井さんの表",
                "小島さんの表", "中村さんの表",
                "大野さんの表", "坂井さんの表",
                "関根さんの表", "島田さんの表",
                "清水さんの表", "高橋さんの表",
                "田中ひろきさんの表", "田中みゆさんの表",
                "田中たいきさんの表", "徳山さんの表",
                "渡邉さんの表", "山口さんの表",]
LABELS_Back = ["相澤さんの裏", "新井さんの裏",
                "江波戸の裏", "長谷川さんの裏",
                "樋口さんの裏", "石井さんの裏",
                "小島さんの裏", "中村さんの裏",
                "大野さんの裏", "坂井さんの裏",
                "関根さんの裏", "島田さんの裏",
                "清水さんの裏", "高橋さんの裏",
                "田中ひろきさんの裏", "田中みゆさんの裏",
                "田中たいきさんの裏", "徳山さんの裏",
                "渡邉さんの裏", "山口さんの裏"]

model_front = get_model(in_shape, nb_classes)
model_back = get_model(in_shape, nb_classes)
#変更必要
model_front.load_weights('D:/過去の研究データ/2023hdf/2023separateLearn/100sheetsNum20FrontEdgesKarnel5-' + str(im_size) + 'pixBatch' + batch + '.hdf5')
model_back.load_weights('D:/過去の研究データ/2023hdf/2023separateLearn/100sheetsNum20BackEdgesKarnel5-' + str(im_size) + 'pixBatch' + batch + '.hdf5')

#評価画像の確率を受け取り、max_scoreよりも大きい値をmax_scoreとして更新する
def findmaxscore(per):
    global max_score
    if per != 100.0:
        if max_score <= per:
            max_score = per 
            
def check_photo(path):
    img = cv2.imread(path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    karnel = np.array(laplace5, np.float64)
    img = cv2.filter2D(img, -1, karnel)
    #画像のリサイズ
    result_img = cv2.resize(img, (im_size, im_size)) 
    # plt.imshow(result_img, cmap = 'gray')
    # plt.show()

    x = np.asarray(result_img)
    x = x.reshape(-1, im_size, im_size, im_color)
    x = x / 255
    
    #画像の予測
    if "/omote" in path:
        pre = model_front.predict([x])[0]
    elif "/ura" in path:
        pre = model_back.predict([x])[0]
    idx = pre.argmax()
    per = (pre[idx] * 100)
    return (idx, per)

def check_photo_str(path_omote, path_ura):
    idx_omote, per_omote = check_photo(path_omote)
    idx_ura, per_ura = check_photo(path_ura)
    #Aさんの表を「Aさん」と「表」に分割する
    omotePerson = LABELS_Front[idx_omote].split("の")
    uraPerson = LABELS_Back[idx_ura].split("の")
    #表の評価画像と裏の評価画像が閾値以上かつ人の名前が一致しているかつ表裏の評価画像が表と裏で一致しているかの判定
    if omotePerson[0] == uraPerson[0] and omotePerson[1] == "表" and uraPerson[1] == "裏":
        print("この手は表:", LABELS_Front[idx_omote], "裏:", LABELS_Back[idx_ura], "なので認証します")
        
        #誤って他人を受入れてしまった確率を配列に格納
        passpercent.append(per_omote)
        passpercent.append(per_ura)
        
        #max_scoreよりも大きい確率かどうかを判定する
        findmaxscore(per_omote)
        findmaxscore(per_ura)
        
    else:
        print('\033[31m' + "認証の結果は表の手:", LABELS_Front[idx_omote], " 裏の手:", LABELS_Back[idx_ura], "なので認証できません" + '\033[0m')
        #正しく他人を拒否した確率を配列に格納する
        notpasspercent.append(per_omote)
        notpasspercent.append(per_ura)
    
if __name__ == '__main__':
    for i in range(100):
        print("\nここからは" + str(i) + "番目の写真です")
        #表と裏の評価画像を渡して認証を行う
        check_photo_str(target_omote[i], target_ura[i])
        if i % 10 == 9:
            print("================================================")
            print("テスト対象の人が変わります")
            print("================================================")

    #他人受入率の配列の中身を表示
    print(passpercent)
    #他人拒否率の配列の中身を表示
    print(notpasspercent)
    print("エッジ画像カーネル5 " + str(im_size) + "px バッチサイズ" + str(batch))
    print("他人受入に用いる個数" + str(len(passpercent)))
    #全体の他人受入率算出用に変数FARに他人受入の個数を格納
    FAR = len(passpercent)
    print("閾値未満で識別したテスト数" + str(len(notpasspercent)))
    #表裏合計、それぞれの他人受入(拒否)率を算出する
    totalpass = len(passpercent) / 200
    totalnotpass = len(notpasspercent) / 200
    print("================================================")
    #未学習の手を閾値未満で識別した割合
    print("他人拒否率" + str(round(totalnotpass * 100, 4)) + "%")
    #未学習の手を閾値以上で識別した割合
    print("他人受入率" + str(round(totalpass * 100, 4)) + "%")


ここからは0番目の写真です
1/1 [==============================] - 0s 67ms/step
認証の結果は表の手: 高橋さんの表  裏の手: 田中ひろきさんの裏 なので認証できません

ここからは1番目の写真です
1/1 [==============================] - 0s 26ms/step
認証の結果は表の手: 高橋さんの表  裏の手: 島田さんの裏 なので認証できません

ここからは2番目の写真です
1/1 [==============================] - 0s 28ms/step
認証の結果は表の手: 高橋さんの表  裏の手: 島田さんの裏 なので認証できません

ここからは3番目の写真です
1/1 [==============================] - 0s 25ms/step
認証の結果は表の手: 高橋さんの表  裏の手: 島田さんの裏 なので認証できません

ここからは4番目の写真です
1/1 [==============================] - 0s 27ms/step
認証の結果は表の手: 関根さんの表  裏の手: 島田さんの裏 なので認証できません

ここからは5番目の写真です
1/1 [==============================] - 0s 25ms/step
認証の結果は表の手: 関根さんの表  裏の手: 島田さんの裏 なので認証できません

ここからは6番目の写真です
1/1 [==============================] - 0s 26ms/step
認証の結果は表の手: 関根さんの表  裏の手: 島田さんの裏 なので認証できません

ここからは7番目の写真です
1/1 [==============================] - 0s 25ms/step
認証の結果は表の手: 関根さんの表  裏の手: 高橋さんの裏 なので認証できません

ここからは8番目の写真です
1/1 [==============================] - 0s 25ms/step
この手は表: 高橋さんの表 裏: 高橋さんの裏 なので認証します

ここからは9番目の写真です
1/1 [=====

In [24]:
#本人受入率評価用のプログラム(閾値を用いずに認証)
import math
import keras 
from keras.models import Sequential
from keras.layers import Dense,Dropout,Flatten
from keras.layers import Conv2D,MaxPooling2D
from keras.optimizers import RMSprop
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image


def def_model(in_shape, nb_classes):
    model = Sequential()
    model.add(Conv2D(32,
              kernel_size = (3, 3),
              activation = 'relu',
              input_shape = in_shape))
    model.add(Conv2D(32, (3, 3), activation = 'relu'))
    model.add(MaxPooling2D(pool_size = (2, 2)))
    model.add(Dropout(0.25))

    model.add(Conv2D(64, (3, 3), activation = 'relu'))
    model.add(Conv2D(64, (3, 3), activation = 'relu'))
    model.add(MaxPooling2D(pool_size = (2, 2)))
    model.add(Dropout(0.25))

    model.add(Flatten())
    model.add(Dense(512, activation = 'relu'))
    model.add(Dropout(0.5))
    model.add(Dense(nb_classes, activation = 'softmax'))
    return model


def get_model(in_shape, nb_classes):
    model = def_model(in_shape, nb_classes)
    model.compile(
        loss = 'categorical_crossentropy',
        optimizer = RMSprop(),
        metrics = ['accuracy'])
    return model

#学習済みの人の評価画像
omote = ["aizawa/right/omote",
        "arai/right/omote",
        "ebato/right/omote",
        "hasegawa/right/omote",
        "higuchi/right/omote",
        "isii/right/omote",
        "kojima/right/omote",
        "nakamura/right/omote",
        "oono/right/omote",
        "sakai/right/omote",
        "sekine/right/omote",
        "shimada/right/omote",
        "shimizu/right/omote",
        "takahashi/right/omote",
        "tanakahiroki/right/omote",
        "tanakamiyu/right/omote",
        "tanakataiki/right/omote",
        "tokuyama/right/omote",
        "watanabe/right/omote",
        "yamaguchi/right/omote"]
ura = ["aizawa/right/ura",
        "arai/right/ura",
        "ebato/right/ura",
        "hasegawa/right/ura",
        "higuchi/right/ura",
        "isii/right/ura",
        "kojima/right/ura",
        "nakamura/right/ura",
        "oono/right/ura",
        "sakai/right/ura",
        "sekine/right/ura",
        "shimada/right/ura",
        "shimizu/right/ura",
        "takahashi/right/ura",
        "tanakahiroki/right/ura",
        "tanakamiyu/right/ura",
        "tanakataiki/right/ura",
        "tokuyama/right/ura",
        "watanabe/right/ura",
        "yamaguchi/right/ura"]

laplace5 = [[-1, -3, -4, -3, -1],
           [-3, 0, 6, 0, -3],
           [-4, 6, 20, 6, -4],
           [-3, 0, 6, 0, -3],
           [-1, -3, -4, -3, -1]]
#表の評価画像と裏の評価画像のパスが格納
target_omote = []
target_ura = []
#誤って他人を受入れてしまった確率が格納
passpercent = []
#正しく他人を拒否した確率が格納
notpasspercent = []
#学習済みの人の中で他人を受入れた場合の警告表示が格納
notIncludeLABEL = []

#変更必要
for k in range(20):
    for i in range(10):
        target_omote.append("D:/過去の研究データ/2023graytest/" + str(omote[k]) + "/gray" + str(i) + ".jpg")
        target_ura.append("D:/過去の研究データ/2023graytest/" + str(ura[k]) + "/gray" + str(i) + ".jpg")

#変更必要
im_size = 128
im_color = 1
in_shape = (im_size, im_size, im_color)
nb_classes = 20
#配列の最大値
max_score = 0.0
batch = "256"

#学習した人のラベル
LABELS_Front = ["相澤さんの表", "新井さんの表",
                "江波戸の表", "長谷川さんの表",
                "樋口さんの表", "石井さんの表",
                "小島さんの表", "中村さんの表",
                "大野さんの表", "坂井さんの表",
                "関根さんの表", "島田さんの表",
                "清水さんの表", "高橋さんの表",
                "田中ひろきさんの表", "田中みゆさんの表",
                "田中たいきさんの表", "徳山さんの表",
                "渡邉さんの表", "山口さんの表",]
LABELS_Back = ["相澤さんの裏", "新井さんの裏",
                "江波戸の裏", "長谷川さんの裏",
                "樋口さんの裏", "石井さんの裏",
                "小島さんの裏", "中村さんの裏",
                "大野さんの裏", "坂井さんの裏",
                "関根さんの裏", "島田さんの裏",
                "清水さんの裏", "高橋さんの裏",
                "田中ひろきさんの裏", "田中みゆさんの裏",
                "田中たいきさんの裏", "徳山さんの裏",
                "渡邉さんの裏", "山口さんの裏"]
#確定ラベル
AbsLABELS = ["相澤さん", "新井さん", "江波戸", "長谷川さん",
             "樋口さん", "石井さん", "小島さん", "中村さん",
             "大野さん", "坂井さん", "関根さん", "島田さん",
             "清水さん", "高橋さん", "田中ひろきさん", "田中みゆさん",
             "田中たいきさん", "徳山さん", "渡邉さん",  "山口さん"]

model_front = get_model(in_shape, nb_classes)
model_back = get_model(in_shape, nb_classes)
#変更必要
model_front.load_weights('D:/過去の研究データ/2023hdf/2023separateLearn/100sheetsNum20FrontEdgesKarnel5-' + str(im_size) + 'pixBatch' + batch + '.hdf5')
model_back.load_weights('D:/過去の研究データ/2023hdf/2023separateLearn/100sheetsNum20BackEdgesKarnel5-' + str(im_size) + 'pixBatch' + batch + '.hdf5')

#評価画像の確率を受け取り、max_scoreよりも大きい値をmax_scoreとして更新する
def findmaxscore(per):
    global max_score
    if per != 100.0:
        if max_score <= per:
            max_score = per
                
def check_photo(path):
    img = cv2.imread(path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    karnel = np.array(laplace5, np.float64)
    img = cv2.filter2D(img, -1, karnel)
    #画像のリサイズ
    result_img = cv2.resize(img, (im_size, im_size))
    #画像の表示
    # plt.imshow(result_img, cmap = 'gray')
    # plt.show()

    x = np.asarray(result_img)
    x = x.reshape(-1, im_size, im_size, im_color)
    x = x / 255
    
    #画像の予測
    if "/omote" in path:
        pre = model_front.predict([x])[0]
    elif "/ura" in path:
        pre = model_back.predict([x])[0]
    idx = pre.argmax()
    per = (pre[idx] * 100)
    return(idx, per)

def check_photo_str(path_omote, path_ura, i): 
    idx_omote, per_omote = check_photo(path_omote)
    idx_ura, per_ura = check_photo(path_ura)
    #Aさんの表を「Aさん」と「表」に分割する
    omotePerson = LABELS_Front[idx_omote].split("の")
    uraPerson = LABELS_Back[idx_ura].split("の")
    #表の評価画像と裏の評価画像が閾値以上かつ人の名前が一致しているかつ表裏の評価画像が表と裏で一致しているかの判定
    if omotePerson[0] == uraPerson[0] and omotePerson[1] == "表" and uraPerson[1] == "裏":
        print("この手は表:", LABELS_Front[idx_omote], "裏:", LABELS_Back[idx_ura], "なので認証します")
        #上記条件を満たしたのに識別を間違えているときの処理
        if i < 10:
            ConfLABEL = AbsLABELS[0]
        elif i < 20:
            ConfLABEL = AbsLABELS[1]
        elif i < 30:
            ConfLABEL = AbsLABELS[2]
        elif i < 40:
            ConfLABEL = AbsLABELS[3]
        elif i < 50:
            ConfLABEL = AbsLABELS[4]
        elif i < 60:
            ConfLABEL = AbsLABELS[5]
        elif i < 70:
            ConfLABEL = AbsLABELS[6]
        elif i < 80:
            ConfLABEL = AbsLABELS[7]
        elif i < 90:
            ConfLABEL = AbsLABELS[8]
        elif i < 100:
            ConfLABEL = AbsLABELS[9]
        elif i < 110:
            ConfLABEL = AbsLABELS[10]
        elif i < 120:
            ConfLABEL = AbsLABELS[11]
        elif i < 130:
            ConfLABEL = AbsLABELS[12]
        elif i < 140:
            ConfLABEL = AbsLABELS[13]
        elif i < 150:
            ConfLABEL = AbsLABELS[14]
        elif i < 160:
            ConfLABEL = AbsLABELS[15]
        elif i < 170:
            ConfLABEL = AbsLABELS[16]
        elif i < 180:
            ConfLABEL = AbsLABELS[17]
        elif i < 190:
            ConfLABEL = AbsLABELS[18]
        elif i < 200:
            ConfLABEL = AbsLABELS[19]

        if ConfLABEL not in LABELS_Front[idx_omote] :
            notIncludeLABEL.append("-" + ConfLABEL + "を" + LABELS[idx_omote] + "だと誤認識-")  
            print('\033[31m' + '識別エラーが起きています' + '\033[0m')
        if ConfLABEL not in LABELS_Back[idx_ura]:
            notIncludeLABEL.append("-" + ConfLABEL + "を" + LABELS[idx_ura] + "だと誤認識-")  
            print('\033[31m' + '識別エラーが起きています' + '\033[0m')

        #本人受入の配列に格納
        passpercent.append(per_omote)
        passpercent.append(per_ura)
        
        #max_scoreよりも大きい確率かどうかを判定する
        findmaxscore(per_omote)
        findmaxscore(per_ura)
        
    else:
        print('\033[31m' + "認証の結果は表の手:", LABELS_Front[idx_omote], " 裏の手:", LABELS_Back[idx_ura], "なので認証できません" + '\033[0m')
        #誤って本人を拒否してしまった人の確率を配列に格納
        notpasspercent.append(per_omote)
        notpasspercent.append(per_ura)
    
if __name__ == '__main__':
    #学習人数が増えたらiのrangeを変更必要
    for i in range(200): 
        print("\nここからは" + str(i) + "番目の写真です")
        #表と裏の評価画像を渡して認証を行う
        check_photo_str(target_omote[i], target_ura[i], i)
        if i % 10 == 9:
            print("================================================")
            print("テスト対象の人が変わります")
            print("================================================")
         
    #他人受入率の配列の中身を表示
    print(passpercent)
    #他人拒否率の配列の中身を表示
    print(notpasspercent)
    print("----------------------------------------------------------------")   
    print("閾値以上で識別したテスト数" + str(len(passpercent)))
    print("閾値未満で識別したテスト数" + str(len(notpasspercent)))
    totalpass = len(passpercent) / 400
    totalnotpass = len(notpasspercent) / 400
    print("================================================")
    #学習済みの人の手を閾値未満で識別した割合
    print("本人拒否率" + str(round(totalnotpass * 100, 4)) + "%")
    #学習済みの人の手を閾値以上で識別した割合
    print("本人受入率" + str(round(totalpass * 100, 4)) + "%")
    #他人受入率の評価と本人拒否率の評価すべてにおける他人受入
    print(notIncludeLABEL)
    print("全体の他人受入率は" + str(round((FAR + len(notIncludeLABEL)) / 600 * 100, 4)) + "%")


ここからは0番目の写真です
1/1 [==============================] - 0s 69ms/step
この手は表: 相澤さんの表 裏: 相澤さんの裏 なので認証します

ここからは1番目の写真です
1/1 [==============================] - 0s 29ms/step
この手は表: 相澤さんの表 裏: 相澤さんの裏 なので認証します

ここからは2番目の写真です
1/1 [==============================] - 0s 26ms/step
この手は表: 相澤さんの表 裏: 相澤さんの裏 なので認証します

ここからは3番目の写真です
1/1 [==============================] - 0s 27ms/step
この手は表: 相澤さんの表 裏: 相澤さんの裏 なので認証します

ここからは4番目の写真です
1/1 [==============================] - 0s 25ms/step
この手は表: 相澤さんの表 裏: 相澤さんの裏 なので認証します

ここからは5番目の写真です
1/1 [==============================] - 0s 35ms/step
この手は表: 相澤さんの表 裏: 相澤さんの裏 なので認証します

ここからは6番目の写真です
1/1 [==============================] - 0s 29ms/step
この手は表: 相澤さんの表 裏: 相澤さんの裏 なので認証します

ここからは7番目の写真です
1/1 [==============================] - 0s 29ms/step
この手は表: 相澤さんの表 裏: 相澤さんの裏 なので認証します

ここからは8番目の写真です
1/1 [==============================] - 0s 29ms/step
この手は表: 相澤さんの表 裏: 相澤さんの裏 なので認証します

ここからは9番目の写真です
1/1 [==============================] - 0s 29ms/step
この手は表: 相澤さんの表 裏: 相澤さんの裏 なので認証します
